import os

from dotenv import load_dotenv
from openai import OpenAI
from pydantic import BaseModel, Field
from typing import List, Optional

# Pydantic model for a descriptive question
class DecriptiveQuestion(BaseModel):
    question: str
    correct_answer: str
    marks: int


# Pydantic model for the descriptive quiz request
class DescriptiveQuizRequest(BaseModel):
    topic: str
    total_marks: int
    num_questions: int

# Pydantic model for the descriptive quiz response generated by AI
class DescriptiveQuizResponse(BaseModel):
    title: str
    total_marks: int
    questions: List[str]


# Setting up the client for OpenAI requests

load_dotenv()
API_KEY = os.getenv("OPENAI_API_KEY")
client = OpenAI(api_key=API_KEY)

SYSTEM_ROLE = "You are a teacher of Bachelor Level Digital Logic Design"


def generate_descriptive_quiz(request: DescriptiveQuizRequest) -> DescriptiveQuizResponse:
    """Generate a descriptive-answer quiz using structured OpenAI response with Pydantic."""

    prompt = f"""
    Create a descriptive-answer quiz on the topic: {request.topic}.
    Total marks: {request.total_marks}.
    Number of questions: {request.num_questions}.
    """

    response = client.responses.parse(
        model="gpt-4o-mini",
        input=[
            {"role": "system", "content": SYSTEM_ROLE},
            {"role": "user", "content": prompt},
        ],
        text_format=DescriptiveQuizResponse,
    )

    return response.output_parsed


# Calling here right now to avoid being called in the inherited files
if __name__ == "__main__":

    req = DescriptiveQuizRequest(
        topic="logic gates",
        total_marks=20,
        num_questions=4
    )

    quiz = generate_descriptive_quiz(req)
    json_quiz = quiz.model_dump_json(indent=2) # a pretty json string which has 2 indents spacing between each level
    print(json_quiz)