import os
from dotenv import load_dotenv
from openai import OpenAI
from pydantic import BaseModel, Field
from typing import List

MODEL_PRICING = {
    "gpt-4o-mini": {
        "input": 0.00015,     # USD per 1K tokens
        "output": 0.0006
    },
    "gpt-5": {
        "input": 0.01,
        "output": 0.03
    }
}


# Pydantic Model defined for a single MCQ Question
class Question(BaseModel):
    """This class defines a BaseModel for the MCQ Question"""
    question: str = Field(..., description="The text of the question")
    options: List[str] = Field(..., description="The list of options given as possible answers")
    correct_answer: str = Field(..., description="The correct answer among the options")


# Pydantic Model defined for input parameters for a quiz generation request with two defaults
class QuizRequest(BaseModel):
    topic: str = "logic gates"
    total_marks: int = 10
    num_questions: int = 5


# Pydantic Model defined for the kind of response we expect for quiz generated by AI
class QuizResponse(BaseModel):
    title: str = Field(..., description="The title of the Response")
    total_marks: int = Field(..., description="The total marks of the response")
    questions: List[Question] # the list of Question class objects


# Setting up the client for OpenAI requests

load_dotenv()
API_KEY = os.getenv("OPENAI_API_KEY")
client = OpenAI(api_key=API_KEY)

SYSTEM_ROLE = "You are a teacher of Bachelor Level Digital Logic Design"


def generate_quiz(request: QuizRequest) -> QuizResponse:
    """This function generates a structured quiz using Pydantic models and OpenAI requests"""

    user_prompt = f"""
    Generate a multiple-choice quiz.
    Topic: {request.topic}
    Total Marks: {request.total_marks}
    Number of Questions: {request.num_questions}

    """

    response = client.responses.parse(
        model="gpt-4o-mini",
        input=[
            {"role": "system", "content": SYSTEM_ROLE},
            {"role": "user", "content": user_prompt}
        ],

        text_format=QuizResponse
    )

    # Calculating the costs
    usage = response.usage

    print(f"Input tokens: {usage.input_tokens} and Input cost: {(usage.input_tokens*0.00015/1000):.6f}")
    print(f"Output tokens: {usage.output_tokens} and Output cost: {usage.output_tokens*0.0006/1000}")
    print(f"Total tokens: {usage.total_tokens} and total cost {(usage.input_tokens*0.00015/1000) + (usage.output_tokens*0.0006/1000)}")

    return response.output_parsed # Ensuring the Python object returned is created by our Pydantic schema


# Calling here right now to avoid being called in the inherited files
if __name__ == "__main__":

    req = QuizRequest(
        topic="logic gates",
        total_marks=10,
        num_questions=5
    )

    quiz = generate_quiz(req)

    print(quiz)

